import Foundation

enum LocalizationStrings {
    static let ja: [String: String] = [
        // App
        "PennyLet": "PennyLet",
        "Track spending, reach goals": "支出を管理して目標を達成",
        "Sign In with Cloud": "クラウドでサインイン",
        "You'll be redirected to sign in securely.": "安全にサインインするためリダイレクトされます。",
        "Continue as Guest": "ゲストとして続ける",
        "Guest Mode": "ゲストモード",
        "Sign in to save your data and unlock all features.": "サインインしてデータを保存し、すべての機能を解放しましょう。",
        "Subscriptions": "サブスクリプション",
        "Active Subscriptions": "アクティブなサブスク",
        "found": "件見つかりました",
        "Yearly": "年間",
        "Detected on this device": "このデバイスで検出",
        "Expired": "期限切れ",
        "No App Store subscriptions found": "App Storeサブスクリプションが見つかりません",
        "Active subscriptions purchased through Apple will appear here automatically.": "Appleを通じて購入したアクティブなサブスクリプションが自動的に表示されます。",
        "Scan for Subscriptions": "サブスクリプションをスキャン",
        "PennyLet can detect your active App Store subscriptions and track them automatically.": "PennyLetはアクティブなApp Storeサブスクリプションを検出し、自動的に追跡します。",
        "Scan Now": "今すぐスキャン",
        "Scan Again": "再スキャン",
        "Scanning subscriptions...": "サブスクリプションをスキャン中...",
        "Checking active entitlements...": "有効な購入情報を確認中...",
        "Reviewing purchase history...": "購入履歴を確認中...",
        "Scanning transaction history...": "取引履歴を確認中...",
        "Subscription Tracker": "サブスクリプション管理",
        "Subscription": "サブスクリプション",
        "Subscription name": "サブスク名",
        "Add Subscription": "サブスクを追加",
        "Track as subscription": "サブスクとして管理",
        "Future charges will be added automatically.": "次回以降の支払いを自動で追加します。",
        "Billing period": "請求周期",
        "Every 2 weeks": "2週間ごと",
        "Custom": "カスタム",
        "Every": "毎",
        "days": "日",
        "weeks": "週間",
        "months": "か月",
        "years": "年",
        "Next charge": "次回支払い",
        "tracked": "件を管理中",
        "App Store subscriptions": "App Storeのサブスク",
        "Manual subscriptions": "手動サブスク",
        "Suggested subscriptions": "候補のサブスク",
        "Suggested from transaction history": "取引履歴からの候補",
        "matches": "件一致",
        "Add manual subscriptions or scan App Store purchases to track renewals.": "手動で追加するか、App Store購入をスキャンして更新を管理しましょう。",
        "For subscriptions outside the App Store, add them manually so PennyLet can renew them for you.": "App Store以外のサブスクは手動で追加すると、PennyLetが次回以降を自動で記録します。",
        "This checks App Store purchase history that iOS allows this app to access.": "このアプリにiOSが許可したApp Store購入情報だけを確認します。",
        "This scan only uses purchase information Apple makes available to this app.": "このスキャンではAppleがこのアプリに提供する購入情報だけを使用します。",
        "biweekly": "隔週",
        "Create Account or Sign In": "アカウント作成 / サインイン",
        "Account Required": "アカウントが必要です",
        "Upgrading to Pro requires an account. Create one or sign in to continue.": "Proへのアップグレードにはアカウントが必要です。アカウントを作成するかサインインしてください。",
        "To upgrade to PennyLet Pro, you need an account. Your data will be saved and synced across devices.": "PennyLet Proにアップグレードするにはアカウントが必要です。データは保存され、デバイス間で同期されます。",
        "Create Account": "アカウント作成",
        "Log In": "ログイン",

        // Onboarding
        "Already have an account? Log In": "アカウントをお持ちですか？ログイン",
        "Your data is stored locally on this device.": "データはこのデバイスにローカルに保存されます。",
        "Skip manual setup by importing a CSV file of your transactions.": "取引のCSVファイルをインポートして手動設定をスキップします。",
        "How PennyLet Works": "PennyLetの使い方",
        "Help": "ヘルプ",
        "Done": "完了",
        "help_balance": "今月の収入から支出を引いた金額です。プラスなら黒字、マイナスなら赤字です。",
        "help_safe_daily": "（月収 − 固定費 − 貯金目標 − 既に使った金額）÷ 残り日数 で計算されます。この金額を超えて使うと月末までに予算が足りなくなります。",
        "help_categories": "今月の支出をカテゴリ別に分類します。どのカテゴリにお金を使いすぎているかが一目でわかります。",
        "AI Analysis": "AI分析",
        "help_ai": "AIがあなたの支出パターンを分析し、日次・週次・月次のインサイトを提供します。無料枠でお試しいただけます。",
        "help_subscriptions": "このデバイスのApp Storeサブスクリプションを自動検出し、月額・年額の合計を表示します。",
        "Welcome to PennyLet": "PennyLetへようこそ",
        "Track your spending, build healthy budgets, and reach your financial goals.": "支出を管理し、健全な予算を立て、目標を達成しましょう。",
        "Back": "戻る",
        "Next": "次へ",
        "Get Started": "始める",
        "Please enter a valid monthly income": "有効な月収を入力してください",
        "Preferences": "設定",
        "Appearance": "デザイン",
        "Color Mode": "カラーモード",
        "Font": "フォント",
        "Region": "地域",
        "Currency": "通貨",
        "Your Budget": "あなたの予算",
        "After tax": "税引後",
        "Essential Bills": "固定費",
        "Rent, utilities, etc.": "家賃、光熱費など",
        "Savings Goal": "貯金目標",
        "Monthly target": "月間目標",
        "Pay Day": "給料日",

        // Dashboard
        "Hello, ": "こんにちは、",
        "Monthly Income": "月収",
        "Good morning, ": "おはようございます、",
        "Good evening, ": "こんばんは、",
        "there": "ゲスト",
        "Safe to Spend Today": "今日使える金額",
        "Spent": "支出",
        "Income": "収入",
        "Balance": "残高",
        "Top Categories": "カテゴリ別",
        "No spending this month": "今月の支出はありません",
        "Recent Activity": "最近の取引",
        "View All": "すべて見る",
        "No transactions yet": "まだ取引がありません",
        "d left": "日残り",
        "% used": "%使用",
        "% of budget used": "予算の%使用",

        // Activity
        "Activity": "取引",
        "Search transactions": "取引を検索",
        "Filter": "フィルター",
        "No Transactions": "取引なし",
        "No Results": "結果なし",
        "Warns you when you're nearing your monthly spending limit.": "月間の支出制限に近づいたときに警告します。",
        "Sends email alerts to the address below. Requires server setup.": "下記のアドレスにメールアラートを送信します。サーバー設定が必要です。",
        "Export CSV": "CSVエクスポート",
        "File name": "ファイル名",
        "Export": "エクスポート",
        "Auto Analysis Help": "自動分析ヘルプ",
        "Auto Analysis automatically generates daily, weekly, and monthly AI spending insights at your scheduled times. Enable it and set your preferred times below.": "自動分析はAIによる日次・週次・月次の支出インサイトを自動生成します。有効にして時間を設定してください。",
        "Export Successful": "エクスポート成功",
        "File saved as": "ファイル名：",
        "Export & Reset": "エクスポート & リセット",
        "Export CSV & Reset": "CSVをエクスポートしてリセット",
        "Reset Without Export": "エクスポートせずにリセット",
        "Save your data as CSV before resetting? All local data will be cleared.": "リセット前にデータをCSVとして保存しますか？すべてのローカルデータが消去されます。",
        "Import CSV": "CSVをインポート",
        "Import Successful": "インポート成功",
        "Import Failed": "インポート失敗",
        "Imported": "インポート完了：",
        "transactions successfully.": "件の取引を正常にインポートしました。",
        "OK": "OK",
        "The file could not be read. Check the format and try again.": "ファイルを読み取れませんでした。フォーマットを確認して再試行してください。",
        "Generate Test Data": "テストデータを生成",
        "Add your first transaction": "最初の取引を追加しましょう",
        "Try a different search": "別のキーワードで検索",

        // Goals
        "Goals": "目標",
        "No Goals Yet": "まだ目標がありません",
        "Set savings goals to track your progress": "貯金目標を設定して進捗を管理しましょう",
        "% complete": "%達成",
        "Goal Details": "目標詳細",
        "Name": "名前",
        "Target Amount": "目標金額",
        "Current Amount": "現在の金額",
        "Frequency": "頻度",
        "Weekly": "毎週",
        "Biweekly": "隔週",
        "Monthly": "毎月",
        "New Goal": "新しい目標",
        "Add Goal": "目標を追加",

        // Budget Health
        "Budget Health": "予算の健全性",
        "Monthly Disposable": "月間自由支出",
        "Spending by Category": "カテゴリ別支出",
        "No spending data this month": "今月の支出データがありません",
        "Income vs Spending": "収入 vs 支出",
        "Remaining": "残り",
        "Safe Daily": "安全な1日額",
        "Days Left": "残り日数",

        // Upgrade
        "PennyLet Pro": "PennyLet Pro",
        "Free": "無料",
        "Pro": "Pro",
        "Plan": "プラン",
        "Yearly (save 40%)": "年間（40%割引）",
        "Processing...": "処理中...",
        "Subscribe": "購読する",
        "Restore Purchases": "購入を復元",
        "More AI Analyses": "より多くのAI分析",
        "30 daily, 15 weekly, 10 monthly, and 3 forecasts every month": "毎月30回のデイリー、15回のウィークリー、10回のマンスリー、3回の予測",
        "Custom Categories": "カスタムカテゴリ",
        "Create your own spending and income categories": "自分だけの支出・収入カテゴリを作成",
        "Spending Forecasts": "支出予測",
        "AI predicts next month's spending based on your history": "過去のデータからAIが来月の支出を予測",
        "Schedule automatic daily, weekly, and monthly AI analysis": "毎日・毎週・毎月のAI分析を自動スケジュール",
        "Forecast": "予測",
        "Spending Forecast": "支出予測",
        "Other": "その他",
        "Weekly Trend": "週間トレンド",
        "Next Month": "来月",
        "Monthly Limit Reached": "月間制限に達しました",
        "Please wait until the first of next month for your usage to refresh.": "来月1日までお待ちください。",
        "Free Uses Exhausted": "無料利用回数を使い切りました",
        "Upgrade to PennyLet Pro for more analyses and unlimited access.": "PennyLet Proにアップグレードして、より多くの分析と無制限のアクセスを。",
        " free left of ": "回の無料利用が残っています（全",
        " uses this month": "回/月）",
        "See AI-predicted spending for next month based on your history.": "過去の履歴に基づいてAIが予測した来月の支出を表示します。",
        "New": "新規",
        "New Category": "新しいカテゴリ",
        "Add": "追加",
        "/mo": "/月",
        "Upgrade": "アップグレード",
        "Get more AI analyses, visual charts, forecasts, and deeper spending insights.": "より多くのAI分析、ビジュアルチャート、予測、より深い支出インサイトを。",
        "Visual Pie Charts": "ビジュアル円グラフ",
        "Beautiful spending breakdown charts in weekly and monthly reports": "週次・月次レポートの美しい支出内訳グラフ",
        "Deeper Spending Insights": "より深い支出インサイト",
        "Detailed patterns, trends, and personalized recommendations": "詳細なパターン、トレンド、パーソナライズされた提案",
        "Just $3.33/month": "月々たった$3.33",
        "AI Spending Insights": "AI支出分析",
        "Daily, weekly, and monthly analysis": "日次・週次・月次の分析",
        "Receipt Scanner": "レシートスキャン",
        "Snap receipts to log expenses instantly": "レシートを撮影して即座に記録",
        "Custom Tags": "カスタムタグ",
        "Organize transactions your way": "取引を自由に整理",
        "Budget Alerts": "予算アラート",
        "Get notified when nearing limits": "予算が近づいたら通知",
        "Advanced Charts": "高度なグラフ",
        "Deeper insights into your spending": "支出をより深く分析",
        "Unable to load pricing. Please try again.": "価格を読み込めませんでした。再試行してください。",
        "No active subscription found.": "有効なサブスクリプションが見つかりません。",
        "Purchase restored! Pro features are now unlocked.": "購入が復元されました！Pro機能のロックが解除されました。",
        "Pro unlocked! Refreshing...": "Proのロック解除！更新中...",

        // Receipt Scanner
        "Scan Receipt": "レシートをスキャン",
        "Take Photo": "写真を撮る",
        "Use": "使用",
        "Take a photo of your receipt": "レシートを撮影してください",
        "We'll extract the merchant, amount, and category automatically.": "店名、金額、カテゴリを自動的に抽出します。",
        "Choose Photo": "写真を選択",
        "Extracted Details": "抽出された情報",
        "Review & Edit": "確認と編集",
        "Tap fields to correct": "タップして修正",
        "Item": "品目",
        "Price": "価格",
        "Total": "合計",
        "Merchant": "店名",
        "Could not load image.": "画像を読み込めませんでした。",
        "Could not prepare image.": "画像を準備できませんでした。",
        "Uploading receipt...": "レシートをアップロード中...",
        "Analyzing with AI...": "AIで分析中...",
        "No text found. Try a clearer photo.": "テキストが見つかりません。より鮮明な写真でお試しください。",
        "Extracting details...": "詳細を抽出中...",
        "Receipt scanning is currently unavailable. Please try again later.": "レシートスキャンは現在利用できません。後でもう一度お試しください。",
        "Could not parse receipt. Try again.": "レシートを解析できませんでした。再試行してください。",

        // Charts / AI
        "Category Breakdown": "カテゴリ別内訳",
        "Daily Spending": "1日の支出",
        "Analysis": "分析",

        // Common labels and settings
        "Language": "言語",
        "Privacy Policy": "プライバシーポリシー",
        "Terms of Use (EULA)": "利用規約（EULA）",
        "Category": "カテゴリ",
        "Budget": "予算",
        "Rate": "レート",
        "Converting...": "換算中...",
        "Could not fetch exchange rate.": "為替レートを取得できませんでした。",
        "Refresh Exchange Rates": "為替レートを更新",
        "Exchange rates updated": "為替レートを更新しました",
        "Date,Type,Category,Amount,Note,Merchant,OriginalCurrency,OriginalAmount,ExchangeRate": "日付,種類,カテゴリ,金額,メモ,店舗,元の通貨,元の金額,為替レート",
        "Purchase pending approval.": "購入は承認待ちです。",
        "Save 40%": "40%お得",
        "mo": "月",
        "Renews": "更新",
        "monthly": "月額",
        "yearly": "年額",
        "weekly": "週額",
        "daily": "日額",
        "subscription": "サブスクリプション",
        "unknown": "不明",

        // AI progress
        "Generate Again": "もう一度生成",
        "Preparing daily insight": "今日の分析を準備中",
        "Building weekly recap": "週間レポートを作成中",
        "Creating monthly insight": "月間分析を作成中",
        "Forecasting spending": "支出を予測中",
        "Reading your spending data": "支出データを読み込み中",
        "Finding patterns and outliers": "傾向と例外を確認中",
        "Writing tailored advice": "あなた向けのアドバイスを作成中",
        "Finalizing your result": "結果を仕上げ中",
        "Almost done": "もうすぐ完了",
        "Still working": "処理中",
        "AI is checking the details": "AIが詳細を確認中",
        "Taking longer than usual": "通常より時間がかかっています",
        "Larger histories can take longer": "履歴が多い場合は時間がかかります",
        "About": "約",
        "left": "残り",
        "Usually": "通常",

        // Help copy
        "This month's income minus expenses. Positive means you're in the green; negative means you're overspending.": "今月の収入から支出を引いた金額です。プラスなら余裕があり、マイナスなら使いすぎの状態です。",
        "(Monthly income − essentials − savings goal − already spent) ÷ days remaining. If you spend more than this per day, you'll run out before month-end.": "（月収 − 固定費 − 貯金目標 − 使用済み金額）÷ 残り日数で計算します。この金額を超えるペースで使うと、月末前に予算が足りなくなります。",
        "Your spending this month broken down by category. Instantly see where your money goes.": "今月の支出をカテゴリ別に表示します。お金の使い先をすぐに確認できます。",
        "AI analyzes your spending patterns and provides daily, weekly, and monthly insights. Free tier includes limited uses.": "AIが支出パターンを分析し、日次・週次・月次のインサイトを届けます。無料プランでは利用回数に上限があります。",
        "Auto-detects App Store subscriptions on this device and shows monthly and yearly totals.": "このデバイスのApp Storeサブスクリプションを検出し、月額・年額の合計を表示します。",

        // Categories
        "Food & Dining": "食事・外食",
        "Groceries": "食料品",
        "Transport": "交通",
        "Shopping": "買い物",
        "Entertainment": "エンタメ",
        "Health": "健康",
        "Bills & Utilities": "請求・公共料金",
        "Rent / Housing": "家賃・住まい",
        "Travel": "旅行",
        "Education": "教育",
        "Gifts": "ギフト",
        "Salary": "給与",
        "Freelance": "フリーランス",
        "Investment": "投資",
        "Gift": "ギフト",

        // Themes and display
        "Light": "ライト",
        "Dark": "ダーク",
        "System": "システム",
        "Sage": "セージ",
        "Ocean": "オーシャン",
        "Sunset": "サンセット",
        "Lavender": "ラベンダー",
        "Forest": "フォレスト",
        "Midnight": "ミッドナイト",
        "Coral": "コーラル",
        "Honey": "ハニー",
        "Plum": "プラム",
        "Mint": "ミント",
        "Sky": "スカイ",
        "Blush": "ブラッシュ",
        "Inter": "Inter",
        "Serif": "セリフ",
        "Rounded": "丸み",
        "Mono": "等幅",

        // Misc
        "Developer Mode": "開発者モード",
        "Type": "種類",
        "All": "すべて",
        "Expense": "支出",
        "Save": "保存",
        "Cancel": "キャンセル",
        "Delete": "削除",
        "Theme": "テーマ",
        "Saving...": "保存中...",
    ]

    static let zh: [String: String] = [
        // App
        "PennyLet": "PennyLet",
        "Track spending, reach goals": "追踪支出，实现目标",
        "Sign In with Cloud": "通过云端登录",
        "You'll be redirected to sign in securely.": "您将被重定向以安全登录。",
        "Continue as Guest": "以游客身份继续",
        "Guest Mode": "游客模式",
        "Sign in to save your data and unlock all features.": "登录以保存数据并解锁所有功能。",
        "Subscriptions": "订阅",
        "Active Subscriptions": "活跃订阅",
        "found": "个",
        "Yearly": "每年",
        "Detected on this device": "在此设备上检测到",
        "Expired": "已过期",
        "No App Store subscriptions found": "未找到App Store订阅",
        "Active subscriptions purchased through Apple will appear here automatically.": "通过Apple购买的活跃订阅将自动显示在这里。",
        "Scan for Subscriptions": "扫描订阅",
        "PennyLet can detect your active App Store subscriptions and track them automatically.": "PennyLet可以检测您活跃的App Store订阅并自动追踪。",
        "Scan Now": "立即扫描",
        "Scan Again": "重新扫描",
        "Scanning subscriptions...": "正在扫描订阅...",
        "Checking active entitlements...": "正在检查有效购买信息...",
        "Reviewing purchase history...": "正在查看购买历史...",
        "Scanning transaction history...": "正在分析交易记录...",
        "Subscription Tracker": "订阅追踪",
        "Subscription": "订阅",
        "Subscription name": "订阅名称",
        "Add Subscription": "添加订阅",
        "Track as subscription": "作为订阅追踪",
        "Future charges will be added automatically.": "之后的扣款会自动添加到记录中。",
        "Billing period": "扣款周期",
        "Every 2 weeks": "每两周",
        "Custom": "自定义",
        "Every": "每",
        "days": "天",
        "weeks": "周",
        "months": "个月",
        "years": "年",
        "Next charge": "下次扣款",
        "tracked": "个已追踪",
        "App Store subscriptions": "App Store 订阅",
        "Manual subscriptions": "手动订阅",
        "Suggested subscriptions": "可能的订阅",
        "Suggested from transaction history": "根据交易记录推测",
        "matches": "次匹配",
        "Add manual subscriptions or scan App Store purchases to track renewals.": "手动添加订阅，或扫描 App Store 购买记录来追踪续费。",
        "For subscriptions outside the App Store, add them manually so PennyLet can renew them for you.": "App Store 之外的订阅可以手动添加，之后 PennyLet 会自动记录续费。",
        "This checks App Store purchase history that iOS allows this app to access.": "这里只会检查 iOS 允许本应用访问的 App Store 购买信息。",
        "This scan only uses purchase information Apple makes available to this app.": "此扫描仅使用 Apple 提供给本应用的购买信息。",
        "biweekly": "每两周",
        "Create Account or Sign In": "创建账户 / 登录",
        "Account Required": "需要账户",
        "Upgrading to Pro requires an account. Create one or sign in to continue.": "升级到Pro需要账户。请创建账户或登录以继续。",
        "To upgrade to PennyLet Pro, you need an account. Your data will be saved and synced across devices.": "要升级到PennyLet Pro，您需要一个账户。您的数据将被保存并在设备间同步。",
        "Create Account": "创建账户",
        "Log In": "登录",

        // Onboarding
        "Already have an account? Log In": "已有账户？登录",
        "Your data is stored locally on this device.": "您的数据本地存储在此设备上。",
        "Skip manual setup by importing a CSV file of your transactions.": "通过导入交易CSV文件跳过手动设置。",
        "How PennyLet Works": "PennyLet使用指南",
        "Help": "帮助",
        "Done": "完成",
        "help_balance": "本月收入减去支出。正数为盈余，负数为亏损。",
        "help_safe_daily": "计算方式：（月收入 − 固定支出 − 储蓄目标 − 已支出）÷ 剩余天数。超过此金额意味着月底前预算不足。",
        "help_categories": "按类别分类本月支出。清楚看到哪个类别超支。",
        "AI Analysis": "AI分析",
        "help_ai": "AI分析您的支出模式，提供每日、每周和每月的洞察。免费试用可用次数。",
        "help_subscriptions": "自动检测此设备上的App Store订阅，显示月度和年度总额。",
        "Welcome to PennyLet": "欢迎使用PennyLet",
        "Track your spending, build healthy budgets, and reach your financial goals.": "追踪支出，建立健康预算，实现财务目标。",
        "Back": "返回",
        "Next": "下一步",
        "Get Started": "开始使用",
        "Please enter a valid monthly income": "请输入有效的月收入",
        "Preferences": "偏好设置",
        "Appearance": "外观",
        "Color Mode": "颜色模式",
        "Font": "字体",
        "Region": "地区",
        "Currency": "货币",
        "Your Budget": "您的预算",
        "After tax": "税后",
        "Essential Bills": "固定支出",
        "Rent, utilities, etc.": "房租、水电等",
        "Savings Goal": "储蓄目标",
        "Monthly target": "月度目标",
        "Pay Day": "发薪日",

        // Dashboard
        "Hello, ": "你好，",
        "Monthly Income": "月收入",
        "Good morning, ": "早上好，",
        "Good evening, ": "晚上好，",
        "there": "访客",
        "Safe to Spend Today": "今日可安全支出",
        "Spent": "已支出",
        "Income": "收入",
        "Balance": "余额",
        "Top Categories": "热门类别",
        "No spending this month": "本月无支出",
        "Recent Activity": "最近交易",
        "View All": "查看全部",
        "No transactions yet": "暂无交易",
        "d left": "天剩余",
        "% used": "%已使用",
        "% of budget used": "预算使用率",

        // Activity
        "Activity": "交易",
        "Search transactions": "搜索交易",
        "Filter": "筛选",
        "No Transactions": "暂无交易",
        "No Results": "无结果",
        "Warns you when you're nearing your monthly spending limit.": "当您接近每月支出限额时发出警告。",
        "Sends email alerts to the address below. Requires server setup.": "发送邮件提醒到下方地址。需要服务器设置。",
        "Export CSV": "导出CSV",
        "File name": "文件名",
        "Export": "导出",
        "Auto Analysis Help": "自动分析帮助",
        "Auto Analysis automatically generates daily, weekly, and monthly AI spending insights at your scheduled times. Enable it and set your preferred times below.": "自动分析会在您设定的时间自动生成每日、每周和每月的AI消费洞察。启用后设置首选时间。",
        "Export Successful": "导出成功",
        "File saved as": "文件保存为：",
        "Export & Reset": "导出 & 重置",
        "Export CSV & Reset": "导出CSV并重置",
        "Reset Without Export": "不导出直接重置",
        "Save your data as CSV before resetting? All local data will be cleared.": "重置前是否将数据保存为CSV？所有本地数据将被清除。",
        "Import CSV": "导入CSV",
        "Import Successful": "导入成功",
        "Import Failed": "导入失败",
        "Imported": "已导入",
        "transactions successfully.": "笔交易。",
        "OK": "确定",
        "The file could not be read. Check the format and try again.": "无法读取文件。请检查格式后重试。",
        "Generate Test Data": "生成测试数据",
        "Add your first transaction": "添加第一笔交易",
        "Try a different search": "尝试其他搜索",

        // Goals
        "Goals": "目标",
        "No Goals Yet": "暂无目标",
        "Set savings goals to track your progress": "设定储蓄目标追踪进度",
        "% complete": "%完成",
        "Goal Details": "目标详情",
        "Name": "名称",
        "Target Amount": "目标金额",
        "Current Amount": "当前金额",
        "Frequency": "频率",
        "Weekly": "每周",
        "Biweekly": "每两周",
        "Monthly": "每月",
        "New Goal": "新建目标",
        "Add Goal": "添加目标",

        // Budget Health
        "Budget Health": "预算健康",
        "Monthly Disposable": "月度可支配",
        "Spending by Category": "分类支出",
        "No spending data this month": "本月无支出数据",
        "Income vs Spending": "收入与支出",
        "Remaining": "剩余",
        "Safe Daily": "日均可花",
        "Days Left": "剩余天数",

        // Upgrade
        "PennyLet Pro": "PennyLet Pro",
        "Free": "免费",
        "Pro": "Pro",
        "Plan": "计划",
        "Yearly (save 40%)": "年度（节省40%）",
        "Processing...": "处理中...",
        "Subscribe": "订阅",
        "Restore Purchases": "恢复购买",
        "More AI Analyses": "更多AI分析",
        "30 daily, 15 weekly, 10 monthly, and 3 forecasts every month": "每月30次每日、15次每周、10次每月、3次预测",
        "Custom Categories": "自定义类别",
        "Create your own spending and income categories": "创建您自己的支出和收入类别",
        "Spending Forecasts": "支出预测",
        "AI predicts next month's spending based on your history": "AI根据您的历史记录预测下月支出",
        "Schedule automatic daily, weekly, and monthly AI analysis": "安排每日、每周和每月的自动AI分析",
        "Forecast": "预测",
        "Spending Forecast": "支出预测",
        "Other": "其他",
        "Weekly Trend": "每周趋势",
        "Next Month": "下月",
        "Monthly Limit Reached": "已达月度上限",
        "Please wait until the first of next month for your usage to refresh.": "请等待下月1日刷新使用次数。",
        "Free Uses Exhausted": "免费使用次数已用完",
        "Upgrade to PennyLet Pro for more analyses and unlimited access.": "升级到PennyLet Pro以获取更多分析和无限访问。",
        " free left of ": "次免费剩余/共",
        " uses this month": "次每月",
        "See AI-predicted spending for next month based on your history.": "查看AI根据您的历史记录预测的下月支出。",
        "New": "新建",
        "New Category": "新类别",
        "Add": "添加",
        "/mo": "/月",
        "Upgrade": "升级",
        "Get more AI analyses, visual charts, forecasts, and deeper spending insights.": "获取更多 AI 分析、可视化图表、预测和更深入的消费洞察。",
        "Visual Pie Charts": "可视化饼图",
        "Beautiful spending breakdown charts in weekly and monthly reports": "每周和每月报告中精美的消费分类图表",
        "Deeper Spending Insights": "更深入的消费洞察",
        "Detailed patterns, trends, and personalized recommendations": "详细的消费模式、趋势和个性化建议",
        "Just $3.33/month": "每月仅$3.33",
        "AI Spending Insights": "AI消费洞察",
        "Daily, weekly, and monthly analysis": "每日、每周、每月分析",
        "Receipt Scanner": "收据扫描器",
        "Snap receipts to log expenses instantly": "拍照即可即时记录消费",
        "Custom Tags": "自定义标签",
        "Organize transactions your way": "按您的方式整理交易",
        "Budget Alerts": "预算提醒",
        "Get notified when nearing limits": "接近限额时收到通知",
        "Advanced Charts": "高级图表",
        "Deeper insights into your spending": "更深入的消费洞察",
        "Unable to load pricing. Please try again.": "无法加载定价，请重试。",
        "No active subscription found.": "未找到有效订阅。",
        "Purchase restored! Pro features are now unlocked.": "购买已恢复！Pro功能现已解锁。",
        "Pro unlocked! Refreshing...": "Pro已解锁！刷新中...",

        // Receipt Scanner
        "Scan Receipt": "扫描收据",
        "Take Photo": "拍照",
        "Use": "使用",
        "Take a photo of your receipt": "拍摄收据照片",
        "We'll extract the merchant, amount, and category automatically.": "我们将自动提取商家、金额和类别。",
        "Choose Photo": "选择照片",
        "Extracted Details": "提取详情",
        "Review & Edit": "检查与编辑",
        "Tap fields to correct": "点击字段进行修正",
        "Item": "项目",
        "Price": "价格",
        "Total": "合计",
        "Merchant": "商家",
        "Could not load image.": "无法加载图片。",
        "Could not prepare image.": "无法准备图片。",
        "Uploading receipt...": "正在上传收据...",
        "Analyzing with AI...": "AI分析中...",
        "No text found. Try a clearer photo.": "未找到文本。请尝试更清晰的照片。",
        "Extracting details...": "正在提取详情...",
        "Receipt scanning is currently unavailable. Please try again later.": "收据扫描当前不可用。请稍后再试。",
        "Could not parse receipt. Try again.": "无法解析收据，请重试。",

        // Charts / AI
        "Category Breakdown": "类别分布",
        "Daily Spending": "每日支出",
        "Analysis": "分析",

        // Common labels and settings
        "Language": "语言",
        "Privacy Policy": "隐私政策",
        "Terms of Use (EULA)": "使用条款（EULA）",
        "Category": "类别",
        "Budget": "预算",
        "Rate": "汇率",
        "Converting...": "正在换算...",
        "Could not fetch exchange rate.": "无法获取汇率。",
        "Refresh Exchange Rates": "刷新汇率",
        "Exchange rates updated": "汇率已更新",
        "Date,Type,Category,Amount,Note,Merchant,OriginalCurrency,OriginalAmount,ExchangeRate": "日期,类型,类别,金额,备注,商家,原币种,原金额,汇率",
        "Purchase pending approval.": "购买正在等待批准。",
        "Save 40%": "省 40%",
        "mo": "月",
        "Renews": "续订",
        "monthly": "每月",
        "yearly": "每年",
        "weekly": "每周",
        "daily": "每天",
        "subscription": "订阅",
        "unknown": "未知",

        // AI progress
        "Generate Again": "重新生成",
        "Preparing daily insight": "正在准备每日洞察",
        "Building weekly recap": "正在生成每周回顾",
        "Creating monthly insight": "正在生成月度洞察",
        "Forecasting spending": "正在预测支出",
        "Reading your spending data": "正在读取支出数据",
        "Finding patterns and outliers": "正在查找模式和异常",
        "Writing tailored advice": "正在撰写个性化建议",
        "Finalizing your result": "正在整理结果",
        "Almost done": "马上完成",
        "Still working": "仍在处理",
        "AI is checking the details": "AI 正在核对细节",
        "Taking longer than usual": "比平时稍久",
        "Larger histories can take longer": "记录较多时可能需要更久",
        "About": "约",
        "left": "剩余",
        "Usually": "通常",

        // Help copy
        "This month's income minus expenses. Positive means you're in the green; negative means you're overspending.": "本月收入减去支出。正数表示还有结余，负数表示已经超支。",
        "(Monthly income − essentials − savings goal − already spent) ÷ days remaining. If you spend more than this per day, you'll run out before month-end.": "（月收入 − 固定支出 − 储蓄目标 − 已花金额）÷ 剩余天数。如果每天超过这个金额，月底前预算就会不够。",
        "Your spending this month broken down by category. Instantly see where your money goes.": "按类别查看本月支出，快速了解钱花在了哪里。",
        "AI analyzes your spending patterns and provides daily, weekly, and monthly insights. Free tier includes limited uses.": "AI 会分析你的支出模式，并提供每日、每周和每月洞察。免费版有使用次数限制。",
        "Auto-detects App Store subscriptions on this device and shows monthly and yearly totals.": "自动检测此设备上的 App Store 订阅，并显示月度与年度合计。",

        // Categories
        "Food & Dining": "餐饮",
        "Groceries": "食品杂货",
        "Transport": "交通",
        "Shopping": "购物",
        "Entertainment": "娱乐",
        "Health": "健康",
        "Bills & Utilities": "账单与公用事业",
        "Rent / Housing": "房租与住房",
        "Travel": "旅行",
        "Education": "教育",
        "Gifts": "礼物",
        "Salary": "工资",
        "Freelance": "自由职业",
        "Investment": "投资",
        "Gift": "礼金",

        // Themes and display
        "Light": "浅色",
        "Dark": "深色",
        "System": "跟随系统",
        "Sage": "鼠尾草",
        "Ocean": "海洋",
        "Sunset": "日落",
        "Lavender": "薰衣草",
        "Forest": "森林",
        "Midnight": "午夜",
        "Coral": "珊瑚",
        "Honey": "蜂蜜",
        "Plum": "梅子",
        "Mint": "薄荷",
        "Sky": "天空",
        "Blush": "腮红",
        "Inter": "Inter",
        "Serif": "衬线体",
        "Rounded": "圆体",
        "Mono": "等宽",

        // Misc
        "Developer Mode": "开发者模式",
        "Type": "类型",
        "All": "全部",
        "Expense": "支出",
        "Save": "保存",
        "Cancel": "取消",
        "Delete": "删除",
        "Theme": "主题",
        "Saving...": "保存中...",
    ]
}
